-- Supabase table for Verum life-calendar markers.
-- Run this once in the Supabase SQL editor for existing projects.

create table if not exists public.verum_life_markers (
  id bigint generated by default as identity primary key,
  week_index integer not null unique check (week_index >= 0),
  label text not null check (char_length(label) between 1 and 40),
  accent text not null check (accent ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.verum_life_markers enable row level security;
